USE master
GO

DROP DATABASE OnlinePostOffice
GO


CREATE DATABASE OnlinePostOffice
GO
 
USE OnlinePostOffice
GO

--- TABLE BRANCHES
CREATE TABLE BRANCHE
(
	branchePin		VARCHAR(10),
	brancheName		VARCHAR(50),
	brancheAddress	VARCHAR(250),
	branchePhone	VARCHAR(50),
	CONSTRAINT PK_BRANCHES PRIMARY KEY(branchePin)
)
GO
--- TABLE OFFICES
CREATE TABLE OFFICE
(
	offficeId		VARCHAR(10),
	officeName		VARCHAR(50),
	officeAddress	VARCHAR(250),
	officePhone		VARCHAR(15),
	officeMail		VARCHAR(50),
	branchePin		VARCHAR(10),
	CONSTRAINT PK_OFFICES PRIMARY KEY(offficeId)
)
GO
ALTER TABLE OFFICE
ADD CONSTRAINT FK_OFFICE_BRANCHE FOREIGN KEY(branchePin) REFERENCES  BRANCHE(branchePin)
GO
--- TABLE ROLE
CREATE TABLE [ROLE]
(
	roleId			VARCHAR(10),
	roleName	 	VARCHAR(50),
	roleDecriptions	VARCHAR(250),
	CONSTRAINT PK_ROLES PRIMARY KEY(roleId)
)
GO
---- TABLE EMPLOYEE
CREATE TABLE EMPLOYEE
(
	employeeId			VARCHAR(10),
	employeeEmail		VARCHAR(50),
	employeePassword	VARCHAR(50),
	employeeFirstName	VARCHAR(50),
	employeeLastName	VARCHAR(50),
	employeeBirthday	DATETIME,
	employeeSex			BIT,
	employeeAddress		VARCHAR(50),
	employeePhone		VARCHAR(15),
	employeeImge		VARCHAR(150),
	offficeId			VARCHAR(10),
	roleId				VARCHAR(10),
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY(employeeId)
)
GO

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_OFFICE FOREIGN KEY(offficeId) REFERENCES  OFFICE(offficeId)
GO

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_ROLE FOREIGN KEY(roleId) REFERENCES  [ROLE](roleId)
GO

--- TABLE CUSTOMER
CREATE TABLE CUSTOMER
(
	customerId			VARCHAR(10),
	customerEmail		VARCHAR(50),
	customerPassword	VARCHAR(50),
	customerFistName	VARCHAR(50),
	customerLastName	VARCHAR(50),
	customerBirthday	DATETIME,
	customerSex			BIT,
	customerAddress		VARCHAR(50),
	customerPhone		VARCHAR(15),
	roleId				VARCHAR(10),
	CONSTRAINT PK_CUSTOMER PRIMARY KEY(customerId)
)
GO

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ROLE FOREIGN KEY(roleId) REFERENCES  [ROLE](roleId)
GO
------- TABLE SERVICESTYPE
CREATE TABLE SERVICESTYPE
(
	servicesId			VARCHAR(10),
	servicesName		VARCHAR(50),
	servicesDecriptions	VARCHAR(250),
	servicesCharges		FLOAT,
	CONSTRAINT PK_SERVICESTYPE PRIMARY KEY(servicesId)
)
GO

------- TABLE DELIVERABLE
CREATE TABLE DELIVERABLE
(
	deliverablePin			VARCHAR(10),
	customerSent			VARCHAR(10),
	deliverableSubject		VARCHAR(50),
	deliverableDecriptions	VARCHAR(250),
	dateSent				DATETIME,
	dateReceived			DATETIME,
	personNameReceived		VARCHAR(50),
	personAddressReceived	VARCHAR(50),
	personPhoneReceived		VARCHAR(50),
	personEmailReceived		VARCHAR(50),
	totalWeight				FLOAT,
	totalDistance			FLOAT,
	totalCharges			FLOAT,
	deliverableStatus		BIT,
	deliverableNote			VARCHAR(250),
	servicesType			VARCHAR(10),
	employeeId				VARCHAR(10),
	CONSTRAINT PK_DELIVERABLE PRIMARY KEY(deliverablePin)
)
GO

ALTER TABLE DELIVERABLE
ADD CONSTRAINT FK_DELIVERABLE_CUSTOMER FOREIGN KEY(customerSent) REFERENCES  CUSTOMER(customerId)
GO

ALTER TABLE DELIVERABLE
ADD CONSTRAINT FK_DELIVERABLE_SERVICESTYPE FOREIGN KEY(servicesType) REFERENCES  SERVICESTYPE(servicesId)
GO

ALTER TABLE DELIVERABLE
ADD CONSTRAINT FK_DELIVERABLE_EMPLOYEE FOREIGN KEY(employeeId) REFERENCES  EMPLOYEE(employeeId)
GO

----------- TABLE DELIVERABLE_DETAIL
CREATE TABLE DELIVERABLE_DETAIL
(
	detailId		VARCHAR(10),
	deliverablePin	VARCHAR(10),
	deliverableName	VARCHAR(50),
	deivrableWeight	FLOAT,
	Decriptions		VARCHAR(250),
	Note			VARCHAR(250),
	CONSTRAINT PK_DELIVERABLE_DETAIL PRIMARY KEY(detailId,deliverablePin)
)
GO

ALTER TABLE DELIVERABLE_DETAIL
ADD CONSTRAINT FK_DELIVERABLE_DETAIL_DELIVERABLE FOREIGN KEY(deliverablePin) REFERENCES  DELIVERABLE(deliverablePin)
GO

----------- TABLE CHARGES_ON_WEIGHT
CREATE TABLE CHARGES_ON_WEIGHT
(
	Id				VARCHAR(10),
	Decriptons		VARCHAR(250),
	weightMin		FLOAT,
	weightMax		FLOAT,
	Charges			FLOAT,
	Note			VARCHAR(250),
	servicesType	VARCHAR(10),
	CONSTRAINT PK_DCHARGES_ON_WEIGHT PRIMARY KEY(Id)
)
GO

ALTER TABLE CHARGES_ON_WEIGHT
ADD CONSTRAINT FK_CHARGES_ON_WEIGHT FOREIGN KEY(servicesType) REFERENCES  SERVICESTYPE(servicesId)
GO

----------- TABLE CHARGES_ON_WEIGHT
CREATE TABLE CHARGES_ON_DISTANCE
(
	Id				VARCHAR(10),
	Decriptons		VARCHAR(250),
	distanceFrom	FLOAT,
	distanceTo		FLOAT,
	Charges			FLOAT,
	Note			VARCHAR(250),
	servicesType	VARCHAR(10),
	CONSTRAINT PK_CHARGES_ON_DISTANCE PRIMARY KEY(Id)
)
GO

ALTER TABLE CHARGES_ON_DISTANCE
ADD CONSTRAINT FK_CHARGES_ON_DISTANCE FOREIGN KEY(servicesType) REFERENCES  SERVICESTYPE(servicesId)
GO

----- TABLE FEEDBACK_AND_CONTACT
CREATE TABLE FEEDBACK_AND_CONTACT
(
	Id			VARCHAR(10),
	[Name]		VARCHAR(50),
	Email		VARCHAR(50),
	Address		VARCHAR(250),
	Phone		VARCHAR(15),
	Subject		VARCHAR(50),
	Contend		VARCHAR(250),
	datesubmit	DATETIME,
	status		BIT,
	CONSTRAINT PK_FEEDBACK_AND_CONTACT PRIMARY KEY(Id)
)
GO
----- TABLE COUNT_VISIT
CREATE TABLE COUNT_VISIT
(
	[count]  INT
)
GO